import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export const RUN_STATE_VERSION = 2;
export const MAX_REPAIRS = 2;

export interface Issue {
  number: number;
  title: string;
  body: string;
  html_url: string;
  state: "open" | "closed";
}

export interface Ticket extends Issue {
  blockers: Issue[];
  repairs: number;
  status: "pending" | "running" | "blocked" | "accepted";
  baseline?: string;
  commit?: string;
  feedback?: string;
}

export interface Session {
  name: string;
  path: string;
  log: string;
}

export interface RunState {
  version: typeof RUN_STATE_VERSION;
  name: string;
  repo: string;
  githubRepo: string;
  origin: string;
  runDir: string;
  worktree: string;
  branch: string;
  baseBranch: string;
  baseSha: string;
  head: string;
  check: string;
  setup?: string;
  timeoutMs: number;
  parent: Issue;
  tickets: Ticket[];
  sessions: Session[];
  finalRepairs: number;
  phase: "setup" | "tickets" | "final" | "publish" | "done";
  status: "running" | "blocked" | "done";
  currentTicket?: number;
  feedback?: string;
  lastError?: string;
  pr?: string;
}

export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function atomicWrite(path: string, text: string): void {
  writeFileSync(`${path}.tmp`, text, { mode: 0o600 });
  renameSync(`${path}.tmp`, path);
}

export function save(state: RunState): void {
  mkdirSync(state.runDir, { recursive: true, mode: 0o700 });
  atomicWrite(join(state.runDir, "state.json"), `${JSON.stringify(state, null, 2)}\n`);
  const rows = state.tickets.map(
    (ticket) =>
      `| #${ticket.number} ${ticket.title.replaceAll("|", "\\|").replaceAll("\n", " ")} | ${ticket.status} | ${ticket.repairs}/${MAX_REPAIRS} | ${ticket.commit ?? ""} |`,
  );
  const active = state.tickets.find((ticket) => ticket.number === state.currentTicket);
  const cli = resolve(import.meta.dirname, "run.mjs");
  const sessions = state.sessions.map(
    (session) =>
      `- ${session.name}\n  - Log: ${session.log}\n  - Reopen: \`cd ${shellQuote(state.worktree)} && pi --session ${shellQuote(session.path)}\``,
  );
  atomicWrite(
    join(state.runDir, "summary.md"),
    [
      `# ${state.name}`,
      "",
      "Generated from state.json. Do not edit this file to change run status.",
      "",
      `Parent: ${state.parent.html_url} (${state.parent.title})`,
      `Status: ${state.status}; phase: ${state.phase}`,
      `Branch: ${state.branch}`,
      `Worktree: ${state.worktree}`,
      `Checks: ${state.check}`,
      state.pr ? `Pull request: ${state.pr}` : "",
      "",
      "## Tickets",
      "",
      "| Ticket | Status | Repairs used | Accepted commit |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
      "## Handoff",
      "",
      state.status === "done"
        ? "Review the final pull request. The runner does not merge it."
        : `Current work: ${active ? `#${active.number} ${active.title}` : state.phase}.`,
      state.lastError ?? "No recorded failure.",
      active?.feedback ?? state.feedback ?? "",
      "",
      "Manual fixes belong in the worktree above. Resume preserves them and reruns checks and review.",
      `Resume: \`node ${shellQuote(cli)} resume ${shellQuote(state.runDir)}\``,
      "",
      "## Worker sessions",
      "",
      "Each attempt uses a fresh session. Missing session files mean Pi failed before persisting a response.",
      `Named-session picker: \`cd ${shellQuote(state.worktree)} && pi --session-dir ${shellQuote(join(state.runDir, "sessions"))} --resume\``,
      "",
      ...sessions,
      "",
    ].join("\n"),
  );
}

export function load(runDir: string): RunState {
  const state = JSON.parse(readFileSync(join(runDir, "state.json"), "utf8")) as RunState;
  if (state.version !== RUN_STATE_VERSION) {
    throw new Error(
      "Unsupported run state version; older snapshots may include issue comments. Preserve any work and start a new run from reviewed issue bodies. Do not change the version by hand.",
    );
  }
  const validBudget = (value: number) =>
    Number.isInteger(value) && value >= 0 && value <= MAX_REPAIRS;
  if (
    state.runDir !== resolve(runDir) ||
    typeof state.origin !== "string" ||
    !Array.isArray(state.tickets) ||
    !Array.isArray(state.sessions) ||
    !validBudget(state.finalRepairs) ||
    !state.tickets.every(
      (ticket) =>
        validBudget(ticket.repairs) &&
        ["pending", "running", "blocked", "accepted"].includes(ticket.status),
    ) ||
    !["setup", "tickets", "final", "publish", "done"].includes(state.phase) ||
    !["running", "blocked", "done"].includes(state.status) ||
    !Number.isInteger(state.timeoutMs) ||
    state.timeoutMs < 1000 ||
    state.timeoutMs > 7_200_000
  ) {
    throw new Error(
      "Unrecognized run state or moved run directory; inspect state.json before continuing",
    );
  }
  return state;
}
